version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      discovery.type: single-node
