apiVersion: v1
kind: Service
metadata:
  name: shortener
spec:
  selector:
    app: shortener
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:
      containers:
        - name: shortener
          image: my-registry.com/shortener:latest
          ports:
            - name: http
              containerPort: 80
