apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myapp-backup
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: myapp-backup:latest
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: secret-access-key
          restartPolicy: OnFailure
        imagePullSecrets:
        - name: my-registry-key
      restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
type: Opaque
data:
  access-key-id: <base64-encoded-access-key-id>
  secret-access-key: <base64-encoded-secret-access-key>
