version: '3'
services:
  app:
    build: .
    environment:
      SPRING_DATA_MONGODB_HOST: db
    depends_on:
      - db
  db:
    image: mongo:latest
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - app
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
