version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: mysql://root:example@mysql:3306/myapp
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: example
