apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  app.properties: |
    server.port=8080
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-app
              image: my-image
              command: ["/bin/sh"]
              args: ["-c", "echo Starting job... && sleep 60 && echo Finishing job..."]
              env:
                - name: APP_PROPERTIES
                  valueFrom:
                    configMapKeyRef:
                      name: my-configmap
                      key: app.properties
          restartPolicy: OnFailure
