version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myapp?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: example