version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.sqlite3
      DB_NAME: /code/db.sqlite3
  db:
    image: postgres:latest
