apiVersion: v2
name: kafka-zookeeper
description: A Helm chart for deploying Kafka with Zookeeper.
version: 0.1.0
appVersion: 1.0

dependencies:
  - name: zookeeper
    version: 0.3.0
    repository: https://charts.helm.sh/stable

  - name: kafka
    version: 12.2.3
    repository: https://charts.helm.sh/incubator

values:
  kafka:
    enabled: true
    replicaCount: 3
    persistence:
      enabled: true
      size: 100Gi
    zookeeper:
      enabled: true
      url: zookeeper:2181
