apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongo-deployment
  labels:
    app: node-mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-mongo
  template:
    metadata:
      labels:
        app: node-mongo
    spec:
      containers:
        - name: node
          image: node:12-alpine
          command: ["npm", "start"]
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: uri
          ports:
            - containerPort: 3000
        - name: mongo
          image: mongo:4.2
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: node-mongo-service
spec:
  selector:
    app: node-mongo
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
