apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: <docker-registry-url>/<image-name>:<image-tag>
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: app.py
          readinessProbe:
            httpGet:
              path: /shorten
              port: 5000
