version: '3'
services:
  app:
    build: .
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: myapp
      DB_USERNAME: root
      DB_PASSWORD: example
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    depends_on:
      - db
      - redis
      - elasticsearch
    ports:
      - "80:80"
    restart: always
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
  redis:
    image: redis:latest
  elasticsearch:
    image: elasticsearch:latest
