version: '3'
services:
  app:
    image: node:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/myapp
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm start
    depends_on:
      - mongo
      - rabbitmq
  mongo:
    image: mongo:latest
    volumes:
      - db-data:/data/db
  rabbitmq:
    image: rabbitmq:latest
