version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: myapp
      DB_USERNAME: root
      DB_PASSWORD: example
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: example
