version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/myapp?user=root&password=example&useSSL=false
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: example
