apiVersion: v2
name: wordpress
description: A Helm chart for deploying WordPress and MySQL
version: 0.1.0
dependencies:
  - name: mysql
    version: 8.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: wordpress
    version: 8.0.0
    repository: https://charts.bitnami.com/bitnami
