version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MSSQL_CONNECTION_STRING: Server=db;Database=myapp;User Id=sa;Password=example;
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: example
      ACCEPT_EULA: Y
